### PR TITLE
Modifications to compile with current ice4j

### PR DESCRIPTION
**Pull request by mondain**
Modified to compile against current ice4j. Formatting rules have not been applied beyond specifically changed lines of code.

### CODE REVIEW

**Comment by ibauersachs** [comment]
lgtm, but, could you please explain why Xyz.build(..) is better than new Xyz(..)?

**Comment by mondain** [comment]
I only assumed there was a reason the team made the RawMessage etc package protected and I wasn't aware of why that decision was made; I added the builders just so that turnserver or other projects could use ice4j without modifying it too much.

**Comment by ibauersachs** [comment]
I'm not really involved with either ice4j nor turnserver, so I don't know. The RawMessage constructor has had package since at least 2010, so I'm wondering how this ever compiled at all... maybe the GSoC student had modified ice4j and his changes never made it into ice4j.

**Comment by ibauersachs** [comment]
See the comment of ed336fd718496610c327f00b108c610cfa297b74 -> "... with patches applied".

**Comment by mondain** [comment]
Does he provide these "patches" somewhere? I did decompile a few of his classes to see if I could spot any insights or tricks, but I found nothing of note. I did not specifically look at RawMessage though. 
While I was writing unit tests for turnserver, I found myself wondering if it was feature complete since some of the work looks unfinished.

**Comment by ibauersachs** [comment]
No idea. @damencho?

**Comment by damencho** [comment]
Hey I have compared the ice4j.jar from ed336fd with the previous one and there are a lot of changes in the jar. Intellij Idea has this feature where you can easily compare jars :)
Anyway I don't have an idea what was going on back then, I will try to investigate that and will come back.

**Pull request merged**
