### PR TITLE
Mavenized

### PR DESCRIPTION
**Pull request by mondain**
- 'git mv' source files to maven directory structure
- 'git mv' resource files from lib to maven directory structure
- added maven pom for turnserver
- added target output directory to git ignores

### CODE REVIEW

**Comment by mondain** [comment]
No source files were modified.

**Comment by ibauersachs** [comment]
Except for that JDK8 profile this looks good, thanks!

(I was looking at the line endings in this repo, they are already LF.)

**Comment by mondain** [comment]
Hopefully its good enough now.

**Comment by mondain** [comment]
@ibauersachs any timeline for merging this PR? I've got other mods ready to submit another PR for to get this working with the latest ice4j and I don't want to clutter up this PR as I know how you all prefer to keep these things self contained.

**Comment by ibauersachs** [comment]
Missed this one, thanks for the ping!

**Comment by mondain** [comment]
Didn't want to be a bother, thanks a bunch!

**Pull request merged**
